"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.typeDefs = void 0;
var graphql_tag_1 = require("graphql-tag");
exports.typeDefs = (0, graphql_tag_1.gql)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  type Asset {\n    id: String!\n    filename: String!\n    mime: String!\n    size: Int!\n    sha256: String\n    status: String!\n    version: Int!\n    createdAt: String!\n    updatedAt: String!\n  }\n\n  type UploadTicket {\n    assetId: String!\n    storagePath: String!\n    uploadUrl: String!\n    expiresAt: String!\n    nonce: String!\n  }\n\n  type DownloadLink {\n    url: String!\n    expiresAt: String!\n  }\n\n  type Query {\n    assets: [Asset!]!\n    asset(id: String!): Asset\n  }\n\n  type Mutation {\n    createUploadUrl(filename: String!, mime: String!, size: Int!): UploadTicket!\n    finalizeUpload(assetId: String!, clientSha256: String!, version: Int!): Asset!\n    getDownloadUrl(assetId: String!): DownloadLink!\n    renameAsset(assetId: String!, newFilename: String!, version: Int!): Asset!\n    shareAsset(assetId: String!, toUserId: String!, canDownload: Boolean!): Boolean!\n  }\n"], ["\n  type Asset {\n    id: String!\n    filename: String!\n    mime: String!\n    size: Int!\n    sha256: String\n    status: String!\n    version: Int!\n    createdAt: String!\n    updatedAt: String!\n  }\n\n  type UploadTicket {\n    assetId: String!\n    storagePath: String!\n    uploadUrl: String!\n    expiresAt: String!\n    nonce: String!\n  }\n\n  type DownloadLink {\n    url: String!\n    expiresAt: String!\n  }\n\n  type Query {\n    assets: [Asset!]!\n    asset(id: String!): Asset\n  }\n\n  type Mutation {\n    createUploadUrl(filename: String!, mime: String!, size: Int!): UploadTicket!\n    finalizeUpload(assetId: String!, clientSha256: String!, version: Int!): Asset!\n    getDownloadUrl(assetId: String!): DownloadLink!\n    renameAsset(assetId: String!, newFilename: String!, version: Int!): Asset!\n    shareAsset(assetId: String!, toUserId: String!, canDownload: Boolean!): Boolean!\n  }\n"])));
var templateObject_1;
